
on:
  schedule:
    - cron:  '0 17,19,21,22 * * 5,6,0,1' # At minute 0 past hour 17, 19, 21, and 22 on Friday, Saturday, Sunday, and Monday. Ref https://crontab.guru/examples.html
name: Scrape Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Scrape
      run: npm run action 
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you